name: flowxml
description: A modern Flutter library that converts XML code into Flutter components with real-time streaming support. Perfect for AI chat interfaces and dynamic content rendering.
version: 1.0.0
homepage: https://github.com/devmaan707/flowxml
repository: https://github.com/devmaan707/flowxml
issue_tracker: https://github.com/devmaan707/flowxml/issues
documentation: https://github.com/devmaan707/flowxml#readme

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  xml: ^6.4.2
  rxdart: ^0.27.7
  cached_network_image: ^3.3.1
  video_player: ^2.8.1
  flutter_markdown: ^0.6.20
  equatable: ^2.0.5
  meta: ^1.10.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  mockito: ^5.4.4
  build_runner: ^2.4.7

flutter:
  uses-material-design: true

topics:
  - xml
  - streaming

  - components
  - widgets
